### PR TITLE
Updates and Ease-of-Use

### PR DESCRIPTION
**Pull request by mikejgray**
Hello Krishnu,

It took some time to try to replicate issue #1 due to a missing requirements.txt. I added that, along with a simple .gitignore, and some formatting. Also, sklearn's Imputer class is soon-to-be deprecated, so I updated the code per the library owner's recommendations.

Please feel free to ignore as you see fit or incorporate these changes into your master branch.

Cheers,
-Mike

### CODE REVIEW

**Comment by krishnu9** [comment]
Hello Mike,

Sorry for reverting this merge but when i run your requirements.txt in a virtual env and run 'python3 classifier.py', I get this error.

Regards,
-Krishnu
error

**Comment by mikejgray** [comment]
Hello Krishnu,

Can you please provide which version of the sklearn library you're using? I suspect it may be a version mismatch. I pulled mostly the latest version of every library. There may also be a conflict that was resolved between Python 3.6 and 3.7.

Take care,
-Mike

**Comment by krishnu9** [comment]
Ok, I updated to python 3.7.3 and the problem still persists. Here are the versions of the modules installed on my env.
numpy = 1.17.2
pandas = 0.25.1
sklearn = 0.21.3
keras = 2.3.0
scipy = 1.3.1

Thanks.

**Comment by mikejgray** [comment]
I rebuilt the virtualenv and ran into the same problem you did, so I reverted to the old Imputer instead of SimpleImputer. I was able to get it working with `from sklearn.impute import SimpleImputer as Imputer` but there are some changes to the class that require further code changes. If you want to go that route it's up to you.

I'll go ahead and open a new PR for that change.

Thanks!
-Mike

**Comment by krishnu9** [comment]
Yes, sure! Feel free to make the changes as you see fit.

**Pull request merged**
